"""Recipe data. There is no admin UI, so this file is the source of truth: on startup every
recipe here is inserted or updated (matched by slug). Recipes removed from this list are
left in the database."""

from sqlalchemy import Connection
from sqlalchemy.dialects.postgresql import insert

from .models import Recipe

RECIPES = [
    {
        "slug": "nikujaga",
        "title": "ほっこり肉じゃが",
        "description": "甘辛い煮汁がじゃがいもにしみた、定番の家庭料理。",
        "category": "和食",
        "cook_time_minutes": 35,
        "servings": 2,
        "image_path": "/images/nikujaga.svg",
        "ingredients": [
            {"name": "牛薄切り肉", "amount": "150g"},
            {"name": "じゃがいも", "amount": "3個"},
            {"name": "玉ねぎ", "amount": "1個"},
            {"name": "にんじん", "amount": "1/2本"},
            {"name": "しらたき", "amount": "100g"},
            {"name": "だし汁", "amount": "300ml"},
            {"name": "醤油", "amount": "大さじ3"},
            {"name": "みりん", "amount": "大さじ2"},
            {"name": "砂糖", "amount": "大さじ1.5"},
        ],
        "steps": [
            "じゃがいもは一口大に切って水にさらす。玉ねぎはくし切り、にんじんは乱切りにする。",
            "鍋に油を熱し、牛肉を炒める。色が変わったら野菜としらたきを加えて炒め合わせる。",
            "だし汁を加えて煮立て、アクを取る。",
            "砂糖・みりん・醤油を加え、落とし蓋をして中火で15分煮る。",
            "火を止めて10分おき、味をなじませたら完成。",
        ],
    },
    {
        "slug": "oyakodon",
        "title": "とろとろ親子丼",
        "description": "半熟卵でふんわりとじた、10分で作れる丼もの。",
        "category": "和食",
        "cook_time_minutes": 15,
        "servings": 1,
        "image_path": "/images/oyakodon.svg",
        "ingredients": [
            {"name": "鶏もも肉", "amount": "100g"},
            {"name": "玉ねぎ", "amount": "1/4個"},
            {"name": "卵", "amount": "2個"},
            {"name": "ごはん", "amount": "丼1杯"},
            {"name": "めんつゆ(3倍濃縮)", "amount": "大さじ2"},
            {"name": "水", "amount": "80ml"},
            {"name": "三つ葉", "amount": "適量"},
        ],
        "steps": [
            "鶏肉は一口大、玉ねぎは薄切りにする。",
            "小さめのフライパンにめんつゆと水を入れて煮立て、鶏肉と玉ねぎを煮る。",
            "鶏肉に火が通ったら溶き卵の2/3を回し入れ、蓋をして30秒。",
            "残りの卵を加えて火を止め、ごはんにのせて三つ葉を飾る。",
        ],
    },
    {
        "slug": "carbonara",
        "title": "濃厚カルボナーラ",
        "description": "生クリームなし、卵とチーズだけで仕上げる本格派。",
        "category": "洋食",
        "cook_time_minutes": 20,
        "servings": 2,
        "image_path": "/images/carbonara.svg",
        "ingredients": [
            {"name": "スパゲッティ", "amount": "200g"},
            {"name": "ベーコン(ブロック)", "amount": "80g"},
            {"name": "卵黄", "amount": "3個"},
            {"name": "全卵", "amount": "1個"},
            {"name": "パルミジャーノ", "amount": "40g"},
            {"name": "黒こしょう", "amount": "たっぷり"},
        ],
        "steps": [
            "ボウルに卵黄・全卵・すりおろしたチーズを混ぜておく。",
            "塩を入れた湯でスパゲッティを表示時間より1分短くゆでる。",
            "フライパンで拍子木切りにしたベーコンをじっくり炒め、脂を出す。",
            "火を止めてパスタとゆで汁大さじ3を加え、少し冷ましてから卵液を和える。",
            "とろみがついたら皿に盛り、黒こしょうをふる。",
        ],
    },
    {
        "slug": "mapo-tofu",
        "title": "しびれる麻婆豆腐",
        "description": "花椒をきかせた、ごはんが止まらない四川風。",
        "category": "中華",
        "cook_time_minutes": 20,
        "servings": 2,
        "image_path": "/images/mapo-tofu.svg",
        "ingredients": [
            {"name": "木綿豆腐", "amount": "1丁"},
            {"name": "豚ひき肉", "amount": "120g"},
            {"name": "長ねぎ", "amount": "1/2本"},
            {"name": "豆板醤", "amount": "小さじ2"},
            {"name": "甜麺醤", "amount": "大さじ1"},
            {"name": "鶏がらスープ", "amount": "200ml"},
            {"name": "水溶き片栗粉", "amount": "大さじ2"},
            {"name": "花椒", "amount": "小さじ1/2"},
        ],
        "steps": [
            "豆腐は2cm角に切り、塩を入れた湯で2分ゆでて水気を切る。",
            "ひき肉をカリッとするまで炒め、豆板醤・甜麺醤を加えて香りを出す。",
            "スープと豆腐を加えて3分煮る。",
            "水溶き片栗粉で2回に分けてとろみをつけ、ねぎと花椒をちらす。",
        ],
    },
    {
        "slug": "green-curry",
        "title": "タイ風グリーンカレー",
        "description": "ココナッツミルクのコクと青唐辛子の辛さがくせになる。",
        "category": "エスニック",
        "cook_time_minutes": 25,
        "servings": 2,
        "image_path": "/images/green-curry.svg",
        "ingredients": [
            {"name": "鶏むね肉", "amount": "200g"},
            {"name": "なす", "amount": "1本"},
            {"name": "パプリカ(赤)", "amount": "1/2個"},
            {"name": "グリーンカレーペースト", "amount": "30g"},
            {"name": "ココナッツミルク", "amount": "400ml"},
            {"name": "ナンプラー", "amount": "大さじ1"},
            {"name": "砂糖", "amount": "小さじ2"},
            {"name": "バジル", "amount": "1枝"},
        ],
        "steps": [
            "鍋にココナッツミルク100mlとペーストを入れ、油が分離するまで炒める。",
            "そぎ切りにした鶏肉を加えて炒め、残りのココナッツミルクを注ぐ。",
            "なすとパプリカを加えて10分煮る。",
            "ナンプラーと砂糖で味を調え、バジルをのせる。",
        ],
    },
    {
        "slug": "strawberry-panna-cotta",
        "title": "いちごのパンナコッタ",
        "description": "ぷるんとなめらか。いちごソースで見た目も華やかに。",
        "category": "デザート",
        "cook_time_minutes": 20,
        "servings": 4,
        "image_path": "/images/strawberry-panna-cotta.svg",
        "ingredients": [
            {"name": "生クリーム", "amount": "200ml"},
            {"name": "牛乳", "amount": "200ml"},
            {"name": "砂糖", "amount": "40g"},
            {"name": "粉ゼラチン", "amount": "5g"},
            {"name": "いちご", "amount": "150g"},
            {"name": "レモン汁", "amount": "小さじ1"},
        ],
        "steps": [
            "粉ゼラチンを水大さじ2でふやかす。",
            "鍋に生クリーム・牛乳・砂糖30gを入れて温め、火を止めてゼラチンを溶かす。",
            "器に注ぎ、冷蔵庫で3時間以上冷やし固める。",
            "いちごを砂糖10g・レモン汁と電子レンジで2分加熱し、ソースにしてかける。",
        ],
    },
    {
        "slug": "egg-fried-rice",
        "title": "パラパラ卵チャーハン",
        "description": "卵とごはんを先に混ぜておくのがコツ。10分で作れる定番の一皿。",
        "category": "中華",
        "cook_time_minutes": 10,
        "servings": 2,
        "image_path": "/images/egg-fried-rice.svg",
        "ingredients": [
            {"name": "ごはん(温かいもの)", "amount": "茶碗2杯(約300g)"},
            {"name": "卵", "amount": "2個"},
            {"name": "長ねぎ", "amount": "1/2本"},
            {"name": "サラダ油", "amount": "大さじ1.5"},
            {"name": "鶏がらスープの素", "amount": "小さじ1"},
            {"name": "塩・こしょう", "amount": "少々"},
            {"name": "醤油", "amount": "小さじ1"},
        ],
        "steps": [
            "長ねぎはみじん切りにする。ボウルに卵を溶き、ごはんを加えてよく混ぜておく。",
            "フライパンに油を入れて強火でしっかり熱する。",
            "卵ごはんを入れ、木べらで切るようにほぐしながら2〜3分炒めてパラパラにする。",
            "長ねぎ・鶏がらスープの素・塩・こしょうを加えてさっと炒め合わせる。",
            "鍋肌から醤油を回し入れ、香りが立ったら火を止めて器に盛る。",
        ],
    },
    {
        "slug": "beef-hamburg-steak",
        "title": "牛肉100%ハンバーグ",
        "description": "つなぎなしで肉のうまみをそのまま。ナイフを入れると肉汁があふれる。",
        "category": "洋食",
        "cook_time_minutes": 30,
        "servings": 2,
        "image_path": "/images/beef-hamburg-steak.svg",
        "ingredients": [
            {"name": "牛ひき肉", "amount": "300g"},
            {"name": "塩", "amount": "小さじ1/2(約3g)"},
            {"name": "黒こしょう", "amount": "少々"},
            {"name": "ナツメグ", "amount": "少々"},
            {"name": "サラダ油", "amount": "小さじ1"},
            {"name": "赤ワイン(または水)", "amount": "大さじ2"},
            {"name": "ケチャップ", "amount": "大さじ2"},
            {"name": "ウスターソース", "amount": "大さじ2"},
            {"name": "バター", "amount": "10g"},
        ],
        "steps": [
            "ひき肉は焼く直前まで冷蔵庫で冷やしておく。冷たいボウルにひき肉と塩を入れ、粘りが出るまで手早く練る。",
            "黒こしょうとナツメグを加えて混ぜ、2等分して厚さ2cmの楕円形にまとめ、中央を軽くくぼませる。",
            "フライパンに油を熱し、中火で3分焼いて焼き色をつける。裏返して蓋をし、弱火で6〜7分蒸し焼きにする。",
            "竹串を刺して透明な肉汁が出れば焼き上がり。赤い汁が出る場合はさらに加熱する。取り出して2分休ませる。",
            "同じフライパンに赤ワインを入れて煮立て、ケチャップ・ウスターソースを加えて少し煮詰め、バターを溶かしてソースにする。",
        ],
    },
    {
        "slug": "houtou",
        "title": "山梨の郷土料理 ほうとう",
        "description": "煮崩れたかぼちゃが溶け込んだ、とろりと甘い味噌仕立ての煮込みうどん。",
        "category": "和食",
        "cook_time_minutes": 40,
        "servings": 2,
        "image_path": "/images/houtou.svg",
        "ingredients": [
            {"name": "ほうとう麺(生)", "amount": "2玉(約300g)"},
            {"name": "かぼちゃ", "amount": "1/8個(約200g)"},
            {"name": "豚バラ薄切り肉", "amount": "100g"},
            {"name": "大根", "amount": "4cm"},
            {"name": "にんじん", "amount": "1/2本"},
            {"name": "白菜", "amount": "2枚"},
            {"name": "しいたけ", "amount": "2枚"},
            {"name": "油揚げ", "amount": "1枚"},
            {"name": "長ねぎ", "amount": "1/2本"},
            {"name": "だし汁", "amount": "900ml"},
            {"name": "味噌", "amount": "大さじ4"},
        ],
        "steps": [
            "かぼちゃは種を取って一口大、大根・にんじんはいちょう切り、白菜はざく切り、しいたけは薄切り、油揚げは短冊切り、豚肉は食べやすく切る。",
            "鍋にだし汁と大根・にんじんを入れて火にかけ、煮立ったら豚肉を加えてアクを取る。",
            "かぼちゃ・しいたけ・油揚げ・白菜を加え、味噌の半量を溶き入れる。",
            "ほうとう麺を下ゆでせずにそのまま入れ、くっつかないようときどき混ぜながら弱めの中火で12〜15分煮込む。",
            "麺がやわらかくなり、かぼちゃが少し煮崩れてとろみが出たら残りの味噌で味を調え、斜め切りの長ねぎを加えてひと煮する。",
        ],
    },
    {
        "slug": "kanitama-don",
        "title": "甘酢あんのかに玉丼",
        "description": "ふんわり焼いたかに玉に、とろりと甘酸っぱいあんをたっぷりかけて。",
        "category": "中華",
        "cook_time_minutes": 15,
        "servings": 2,
        "image_path": "/images/kanitama-don.svg",
        "ingredients": [
            {"name": "卵", "amount": "4個"},
            {"name": "かに風味かまぼこ", "amount": "6本(約60g)"},
            {"name": "長ねぎ", "amount": "1/3本"},
            {"name": "ごはん", "amount": "丼2杯"},
            {"name": "ごま油", "amount": "大さじ1.5"},
            {"name": "塩・こしょう", "amount": "少々"},
            {"name": "グリーンピース", "amount": "適量"},
            {"name": "【甘酢あん】水", "amount": "150ml"},
            {"name": "【甘酢あん】鶏がらスープの素", "amount": "小さじ1"},
            {"name": "【甘酢あん】醤油", "amount": "大さじ1"},
            {"name": "【甘酢あん】酢", "amount": "大さじ1"},
            {"name": "【甘酢あん】砂糖", "amount": "大さじ1"},
            {"name": "【甘酢あん】ケチャップ", "amount": "大さじ1"},
            {"name": "【甘酢あん】片栗粉(同量の水で溶く)", "amount": "大さじ1"},
        ],
        "steps": [
            "かにかまは手で細かくほぐし、長ねぎは斜め薄切りにする。卵を溶いてかにかま・ねぎ・塩・こしょうを混ぜる。",
            "小鍋に甘酢あんの材料(片栗粉以外)を入れて煮立て、水溶き片栗粉でとろみをつける。",
            "フライパンにごま油の半量を強火で熱し、卵液の半量を流し入れる。大きく3〜4回混ぜて丸く形を整える。",
            "半熟のうちにごはんの上へ滑らせるようにのせる。もう1人分も同様に焼く。",
            "熱々の甘酢あんをたっぷりかけ、グリーンピースを散らす。",
        ],
    },
    {
        "slug": "black-vinegar-hiyashi-chuka",
        "title": "黒酢だれの冷やし中華",
        "description": "まろやかなコクのある黒酢だれで、さっぱりなのに食べごたえのある一皿。",
        "category": "中華",
        "cook_time_minutes": 25,
        "servings": 2,
        "image_path": "/images/black-vinegar-hiyashi-chuka.svg",
        "ingredients": [
            {"name": "中華生麺", "amount": "2玉"},
            {"name": "ハム", "amount": "4枚"},
            {"name": "きゅうり", "amount": "1本"},
            {"name": "トマト", "amount": "1個"},
            {"name": "錦糸卵(なければ市販のものでOK)", "amount": "卵2個分(市販品なら約40g)"},
            {"name": "砂糖(錦糸卵用)", "amount": "小さじ1/2"},
            {"name": "紅しょうが・白いりごま", "amount": "適量"},
            {"name": "【黒酢だれ】黒酢", "amount": "大さじ4"},
            {"name": "【黒酢だれ】醤油", "amount": "大さじ3"},
            {"name": "【黒酢だれ】砂糖", "amount": "大さじ2"},
            {"name": "【黒酢だれ】ごま油", "amount": "大さじ1"},
            {"name": "【黒酢だれ】水", "amount": "大さじ3"},
            {"name": "【黒酢だれ】おろし生姜", "amount": "小さじ1/2"},
        ],
        "steps": [
            "黒酢だれの材料を混ぜ、砂糖が溶けたら冷蔵庫で冷やしておく。",
            "卵に砂糖を混ぜて薄焼き卵を焼き、細切りにして錦糸卵にする(難しければ市販の錦糸卵でOK)。ハム・きゅうりは細切り、トマトはくし切りにする。",
            "麺を表示どおりにゆで、冷水でもみ洗いしてぬめりを取り、氷水でしっかり締めて水気をよく切る。",
            "器に麺を盛り、ハム・きゅうり・錦糸卵・トマトを彩りよく放射状にのせる。",
            "食べる直前に黒酢だれをかけ、紅しょうがと白ごまを添える。",
        ],
    },
    {
        "slug": "pork-salmon-miso-chanko",
        "title": "豚と鮭の味噌ちゃんこ鍋",
        "description": "豚のうまみと鮭の脂が溶け込んだ味噌スープ。仕上げのバターで北海道風に。",
        "category": "和食",
        "cook_time_minutes": 35,
        "servings": 3,
        "image_path": "/images/pork-salmon-miso-chanko.svg",
        "ingredients": [
            {"name": "豚バラ薄切り肉", "amount": "200g"},
            {"name": "生鮭(切り身)", "amount": "2切れ"},
            {"name": "塩(鮭の下処理用)", "amount": "少々"},
            {"name": "白菜", "amount": "1/8株"},
            {"name": "長ねぎ", "amount": "1本"},
            {"name": "にんじん", "amount": "1/2本"},
            {"name": "ごぼう", "amount": "1/3本"},
            {"name": "しいたけ", "amount": "4枚"},
            {"name": "えのき", "amount": "1袋"},
            {"name": "木綿豆腐", "amount": "1/2丁"},
            {"name": "油揚げ", "amount": "1枚"},
            {"name": "ニラ", "amount": "1/2束"},
            {"name": "バター(お好みで)", "amount": "10g"},
            {"name": "【スープ】だし汁", "amount": "1000ml"},
            {"name": "【スープ】味噌", "amount": "大さじ4"},
            {"name": "【スープ】酒", "amount": "大さじ2"},
            {"name": "【スープ】みりん", "amount": "大さじ1"},
            {"name": "【スープ】鶏がらスープの素", "amount": "小さじ1"},
            {"name": "【スープ】おろしにんにく", "amount": "小さじ1/2"},
        ],
        "steps": [
            "鮭は3等分に切って塩をふり、10分おいて出てきた水気を拭く。熱湯をさっと回しかけて臭みを取る(霜降り)。",
            "白菜・長ねぎはざく切り、にんじんは輪切り、ごぼうはささがき、しいたけは石づきを取り、えのきはほぐす。豆腐と油揚げは食べやすく切り、ニラは5cm長さに切る。",
            "土鍋にスープの材料を入れて混ぜながら煮立て、ごぼう・にんじん・白菜の芯を入れて5分煮る。",
            "豚肉を加えてアクを取り、白菜の葉・長ねぎ・きのこ・豆腐・油揚げを入れて5分煮る。",
            "鮭を加えて弱めの中火で4〜5分煮る(煮すぎると身が崩れて硬くなる)。最後にニラをのせ、お好みでバターを落とす。",
            "〆はうどんや、ごはんと溶き卵で雑炊にするのがおすすめ。",
        ],
    },
]

_UPDATABLE = [
    "title",
    "description",
    "category",
    "cook_time_minutes",
    "servings",
    "image_path",
    "ingredients",
    "steps",
]


def seed_recipes(conn: Connection) -> None:
    stmt = insert(Recipe).values(RECIPES)
    stmt = stmt.on_conflict_do_update(
        index_elements=[Recipe.slug],
        set_={name: stmt.excluded[name] for name in _UPDATABLE},
    )
    conn.execute(stmt)
